apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uptermd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: uptermd
    spec:
      containers:
      - name: uptermd
        image: jingweno/uptermd
        imagePullPolicy: Always
        args: ["--host", "0.0.0.0:22", "--socket-dir", "/sockets"]
        ports:
        - containerPort: 22 # uptermd
        readinessProbe:
           tcpSocket:
             port: 22
           periodSeconds: 10
        livenessProbe:
           tcpSocket:
             port: 22
           periodSeconds: 20
        volumeMounts:
            - mountPath: /sockets
              name: socket-dir
      volumes:
      - name: socket-dir
        emptyDir:
          medium: Memory
---

apiVersion: v1
kind: Service
metadata:
  name: uptermd
spec:
  type: LoadBalancer
  selector:
    app: uptermd
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
    name: uptermd
