apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: uptermd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: uptermd
    spec:
      containers:
      - name: uptermd
        image: jingweno/uptermd
        imagePullPolicy: Always
        args: ["--host", "0.0.0.0:22", "--host-key", "/host-keys/ed25519_key", "--socket-dir", "/sockets"]
        ports:
        - containerPort: 22 # uptermd
        readinessProbe:
           tcpSocket:
             port: 22
           periodSeconds: 10
        livenessProbe:
           tcpSocket:
             port: 22
           periodSeconds: 20
        volumeMounts:
            - mountPath: /sockets
              name: socket-dir
            - mountPath: /host-keys
              name: host-keys
      volumes:
      - name: socket-dir
        emptyDir:
          medium: Memory
      - name: host-keys
        secret:
          secretName: host-keys
          defaultMode: 0600
---

apiVersion: v1
kind: Service
metadata:
  name: uptermd
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: uptermd
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
    name: uptermd
